# permissions for end users to view intermineinstances.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: intermineinstance-viewer-role
rules:
- apiGroups:
  - intermine.intermine.org
  resources:
  - intermineinstances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - intermine.intermine.org
  resources:
  - intermineinstances/status
  verbs:
  - get
