
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - intermine.intermine.org
  resources:
  - intermineinstances
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - intermine.intermine.org
  resources:
  - intermineinstances/finalizers
  verbs:
  - update
- apiGroups:
  - intermine.intermine.org
  resources:
  - intermineinstances/status
  verbs:
  - get
  - patch
  - update
