apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-admin
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: default
  namespace: argo
---
apiVersion: v1
data:
  config: 'containerRuntimeExecutor: pns'
kind: ConfigMap
metadata:
  name: workflow-controller-configmap
  namespace: argo
