apiVersion: apps/v1
kind: Deployment
metadata:
  name: demon
  labels:
    app: demon
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demon
  template:
    metadata:
      labels:
        app: demon
    spec:
      containers:
      - name: demon
        image: intermine/demon:latest
        ports:
        - containerPort: 9991
        env:
        - name: MESSENGER
          value: "NATS"
        - name: NATS_ENDPOINT
          value: "nats://nats.nats.svc.cluster.local:4222"
---
apiVersion: v1
kind: Service
metadata:
  name: demon
  labels:
    app: demon
spec:
  selector:
    app: demon
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9991
      targetPort: 9991

