apiVersion: v1
kind: Service
metadata:
  name: traefik
spec:
  type: NodePort
  ports:
  - port: 9000
    name: traefik
    targetPort: "traefik"
    protocol: TCP
    nodePort: 32090
  - port: 80
    name: web
    targetPort: "web"
    protocol: TCP
    nodePort: 32080
  - port: 443
    name: websecure
    targetPort: "websecure"
    protocol: TCP
    nodePort: 32443
