# Modified copy from https://github.com/intermine/docker-intermine-gradle
version: "3"
services:
  postgres:
    container_name: intermine-postgres
    image: intermine/postgres:latest
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  solr:
    container_name: intermine-solr
    image: intermine/solr
    environment:
      - MEM_OPTS=${MEM_OPTS:-"-Xmx2g -Xms1g"}
      - MINE_NAME=${MINE_NAME:-biotestmine}
    user: ${UID:-1000}:${GID:-1000}
    volumes:
      - ./data/solr:/var/solr

  # tomcat:
  #   container_name: intermine-tomcat
  #   image: intermine/tomcat
  #   environment:
  #     - MEM_OPTS=${MEM_OPTS:-"-Xmx1g -Xms500m"}
  #   ports:
  #     - ${TOMCAT_HOST_PORT:-9999}:${TOMCAT_PORT:-8080}

# volumes:
#   PostgresDBData:
#   SolrDBData:
#   MineData:
#   MineConfigs:
