apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-{{.Release.Name}}-tools
  labels:
    {{- include "intermineinstance.labels" . | nindent 4 }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard-rwo

