openapi: 3.0.2
info:
  version: 1.0.0
  title: Compose
  # termsOfService: 'https://example.com/terms/'
  contact:
    email: dev@lists.intermine.org
    url: 'http://intermine.org/contact/'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://raw.githubusercontent.com/intermine/design-materials/ff1ec6bf/logos/intermine/intermine-300x37.png'
  description: >
    This is OpenAPI specification for InterMine Cloud

    # Introduction

externalDocs:
  description: Find out more about intermine cloud
  url: 'https://github.com/intermine/intermine_cloud'
tags:
  - name: auth
    description: Auth operations
  - name: user
    description: User operations
  - name: data
    description: Data operations
  - name: template
    description: Template operations
  - name: mine
    description: Mine operations
  - name: file
    description: File operations
  - name: job
    description: Job operations
servers:
  - url: "https://localhost:{port}/v1"
    description: Localhost server
    variables:
      port:
        default: "1404"
        description: "port"
  - url: "https://{subdomain}.{domain}:{port}/v1"
    description: Online server
    variables:
      domain:
        default: "intremine.org"
        description: "domain"
      subdomain:
        default: "cloud"
        description: "sub domain"
      port:
        default: "443"
        description: "port"
paths:
  /auth/:
    $ref: paths/auth.yaml
  /user/:
    $ref: paths/user.yaml
  /job/:
    $ref: paths/job.yaml
  /data/:
    $ref: paths/data.yaml
  /template/:
    $ref: paths/template.yaml
  /mine/:
    $ref: paths/mine.yaml
  /file/:
    $ref: paths/file.yaml
components:
  securitySchemes:
    bearerAuth:
      $ref: components/securitySchemes/bearer_auth.yaml
